### ISSUE TITLE
IMU - Radar Extrinsic Calibration Matrix

### ISSUE THREAD

**Issue by hoangvietdo** [chy525/DRIO-dataset#2]
Hi,

Thank you for making the dataset publicly available.

I was wondering if it's possible to obtain the extrinsic calibration between the IMU and Radar, as I couldn't find these parameters anywhere in the provided Google Drive.

**Comment by chy525** [comment]
Hi,


Thank you for your interest in our research article.

# Radar-Lidar extrinsic parameters
t = [0.073, -0.0103, 0.137];
R = [-0.013746383632443, 0.999905514004713, 0;
   -0.999905514004713, -0.013746383632443, 0;
   0, 0, 1.00];
PointsInLidar = R * PointsInRadar + t';

# Radar-IMU extrinsic parameters
R = [0, -1, 0;
   1, 0, 0;
   0, 0, 1];
t = [-0.032, 0.038, 0.084];


Best regards,


Hongyu Chen
Tsinghua University







At 2024-08-15 15:03:24, "Viet" ***@***.***> wrote:

Hi,

Thank you for making the dataset publicly available.

I was wondering if it's possible to obtain the extrinsic calibration between the IMU and Radar, as I couldn't find these parameters anywhere in the provided Google Drive.
